{
 "title": "Anker Solix",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "site_id",
    "label": "Site ID",
    "query": {
     "query": "label_values(anker_solix_statistics_total_power,site_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anker_solix_solarbank_battery_power{site_id=\"$site_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery charging power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anker_solix_solarbank_total_charging_power{site_id=\"$site_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery input power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anker_solix_solarbank_total_photovoltaic_power{site_id=\"$site_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery output power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anker_solix_solarbank_total_output_power{site_id=\"$site_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total home power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anker_solix_grid_to_home_power{site_id=\"$site_id\"} + anker_solix_solarbank_total_output_power{site_id=\"$site_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Generation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anker_solix_statistics_total_power{site_id=\"$site_id\"}",
     "legendFormat": "Bank"
    }
   ]
  },
  { "title": "Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Home grid power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "anker_solix_grid_to_home_power{site_id=\"$site_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Home total power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "anker_solix_grid_to_home_power{site_id=\"$site_id\"} + anker_solix_solarbank_total_output_power{site_id=\"$site_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Photovoltaic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Power generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "anker_solix_solarbank_total_photovoltaic_power{site_id=\"$site_id\"}",
     "legendFormat": "Module"
    }
   ]
  },
  {
   "title": "Power generation per Module",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "anker_solix_solar_power_1{site_id=\"$site_id\"}",
     "legendFormat": "Module 1"
    },
    {
     "expr": "anker_solix_solar_power_2{site_id=\"$site_id\"}",
     "legendFormat": "Module 2"
    },
    {
     "expr": "anker_solix_solar_power_3{site_id=\"$site_id\"}",
     "legendFormat": "Module 3"
    },
    {
     "expr": "anker_solix_solar_power_4{site_id=\"$site_id\"}",
     "legendFormat": "Module 4"
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "anker_solix_solarbank_battery_power{site_id=\"$site_id\"}",
     "legendFormat": "Bank"
    }
   ]
  },
  {
   "title": "Input Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "anker_solix_solarbank_total_photovoltaic_power{site_id=\"$site_id\"}",
     "legendFormat": "Bank"
    }
   ]
  },
  {
   "title": "Charging Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "anker_solix_solarbank_total_charging_power{site_id=\"$site_id\"}",
     "legendFormat": "Bank"
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "anker_solix_solarbank_total_output_power{site_id=\"$site_id\"}",
     "legendFormat": "Bank"
    }
   ]
  }
 ]
}